[package]
name = "cubit"
version = "1.3.0"
cairo-version = "^2.8.4"
edition = "2023_10"
description = "Math library in Cairo using a 64.64 fixed point representation"
homepage = "https://github.com/influenceth/cubit"

[lib]
sierra = false # Enable Sierra codegen.
casm = false   # Enable CASM codegen.

[dependencies]
starknet = "2.8.4"
cairo_test = "2.8.4"
